### ISSUE TITLE
Margin testnet still working?

### ISSUE THREAD

**Issue by spyke555** [LUCIT-Systems-and-Development/unicorn-binance-rest-api#23]
Looking to test some margin functions like loan creation and repayment, so I set the exchange to 'binance.com-margin-testnet'

However when I make a request for something like get_margin_account, it raises an exception due to incorrect API key.

I used keys generated here : https://testnet.binance.vision/ which is the URL pointed to in the docs for the binance margin testnet.

Given this testnet was added to the library two years ago, I am now wondering if the margin testnet is even still available? How are you all testing margin functionality short of doing it live on testnet?

Thanks for the great library!

**Comment by oliver-zehentleitner** [comment]
I think this key is only for SPOT. I remember there is a second testnet for futures: https://testnet.binancefuture.com/en/register

For margin i did not find a platform to get private keys. 

I personal code on live system since there was sometimes small differences which forced me to test everything twice. so i use a seconds account with a small deposit.

**Comment by spyke555** [comment]
Okay,

I've been testing order open and close on spot testnet, so all I have left is loan and repay. Should be easy enought to test live.

Thanks!
